proyectos/comun/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


urlpatterns = patterns('comun.views',
    url(r'^refrescar_captcha/$', 'refrescar_captcha', name='refrescar_captcha'),
    url(r'^confirmar/$', 'confirmar', name='confirmar'),
    url(r'^restablecer/$', 'restablecer_contrasena', name='restablecer_contrasena'),
    url(r'^municipios/$', 'municipios', name='obtener_municipios'),
    url(r'^parroquias/$', 'parroquias', name='obtener_parroquias'),
)

comun_patterns = urlpatterns

proyectos/proyectos/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import patterns, include, url

from proyectos_app.urls import proyectos_app_paterns
from comun.urls import comun_patterns


urlpatterns = patterns('',
    url(r'^recursos/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^comun/', include(comun_patterns)),
    url(r'^captcha/', include('captcha.urls')),
    ) + proyectos_app_paterns

proyectos/proyectos_app/models/abstracts.py
# -*- coding: utf-8 -*-
'''
Created on 26/04/2014

@author: rtorres
'''
from django.db import models

from proyectos_app.models.miscelaneos import Profesion
from proyectos_app.models.preguntaSeguridad import PreguntaSeguridad


class Persona(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    tipo_cedula = models.CharField(max_length=1)
    cedula = models.CharField(max_length=8)

    class Meta:
        unique_together = (("tipo_cedula", "cedula"),)
        abstract = True


class PersonaSolicitante(Persona):
    '''
    Clase base para los modelos que incluyen datos de personas asociadas a los proyectos
    '''
    correo = models.EmailField(max_length=255)

    class Meta(Persona.Meta):
        pass


class Recupera(models.Model):

    pregunta_seguridad = models.ForeignKey(PreguntaSeguridad)
    respuesta_seguridad = models.CharField('respuesta', max_length=255)

    class Meta:
        abstract = True


class Seguridad(Recupera):

    contrasena = models.CharField(max_length=255)
    conf_contrasena = models.CharField(max_length=255)
    nueva_contrasena = models.CharField(max_length=255)
    usuario = models.IntegerField()

    class Meta:
        abstract = True


class InformacionContacto(models.Model):

    telefono = models.CharField('teléfono', max_length=20)
    correo = models.EmailField(max_length=255)
    direccion = models.CharField('dirección', max_length=255)

    def __unicode__(self):
        return self.correo

    class Meta:
        abstract = True

    @property
    def dominio(self):
        return self.correo[self.correo.find('@'):]


class DireccionFiscal(models.Model):
    estado = models.CharField(max_length=32)
    municipio = models.CharField(max_length=32)
    parroquia = models.CharField(max_length=32)
    zona_postal = models.CharField('zona postal', max_length=4)

    class Meta:
        abstract = True


class InfoEmpleado(models.Model):
    '''
    Modelo que resguarda la información de un empleado
    '''
    profesion = models.ForeignKey(Profesion)
    cargo = models.CharField(max_length=128)
    dependencia = models.CharField(max_length=128)

    class Meta:
        abstract = True

proyectos/proyectos_app/views/dashboardViews.py
# -*- coding: utf-8 -*-
'''
Created on 02/05/2014

@author: rtores
'''
from django.contrib.auth import logout
from django.core.urlresolvers import reverse
from django.views.generic.base import TemplateView, RedirectView

from proyectos_app.views.utilsView import LoginRequeridoMixin, inicializar_session


class DashboardView(LoginRequeridoMixin, TemplateView):
    template_name = 'proyectos/dashboard.html'

    def get_context_data(self, **kwargs):
        inicializar_session(self)
        return TemplateView.get_context_data(self, **kwargs)


class LogOutView(RedirectView):

    permanent = False
    query_string = True

    def get_redirect_url(self):
        logout(self.request)
        return reverse('login')

proyectos/proyectos_app/views/loginViews.py
# -*- coding: utf-8 -*-
'''
Created on 28/04/2014

@author: rtorres
'''

from django.conf import settings
from django.contrib import messages
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.views.generic.edit import FormView

from comun.aplicacion_comun import validar_usuario
from comun.mensajes import MENSAJES_SOLICITANTE
from proyectos_app.constantes import usuario_solicitante
from proyectos_app.forms.solicitanteForms import FormularioLoginSolicitante
from proyectos_app.models.usuarioSolicitante import UsuarioSolicitante
from proyectos_app.views.utilsView import inicializar_session


TEMP_FORM = 'proyectos/login.html'
TEMP_DASH = 'proyectos/dashboard.html'


class LoginView(FormView):
    '''
    Muestra el formulario de ingreso a la aplicación para los solicitantes de proyectos
    @return: El formulario de ingreso a la aplicación para los proyectos
    '''
    form_class = FormularioLoginSolicitante
    template_name = TEMP_FORM
    model = UsuarioSolicitante

    def form_valid(self, form):
        respuesta = None
        nombre_usuario = form.cleaned_data['tipo_per'] + "-" + form.cleaned_data['rif'] + "-" + \
            form.cleaned_data['rif_fin']
        contrasena = form.cleaned_data['contrasena']
        usuario = validar_usuario(nombre_usuario, contrasena)
        if('error' in usuario):
            messages.error(self.request, usuario['error'])
            respuesta = FormView.form_invalid(self, form)
        else:
            try:
                solicitante = UsuarioSolicitante.objects.get(usuario=usuario['id'])
            except UsuarioSolicitante.DoesNotExist:
                messages.error(self.request, MENSAJES_SOLICITANTE["LOGIN_USUARIO_NO_VALIDO"])
                respuesta = FormView.form_invalid(self, form)
            if respuesta is None:
                self.request.session[usuario_solicitante] = solicitante
                self.request.session['permisos'] = usuario['permisos']
                self.request.session.set_expiry(settings.SESSION_EXPIRY)
                inicializar_session(self)
                respuesta = render_to_response(TEMP_DASH, {},
                                context_instance=RequestContext(self.request))
        return respuesta

proyectos/proyectos/templates/proyectos/base.html
{% extends "base.html" %}


{% block datos_usuario %}
	<div class="PanelUsuario">
		<div class="NombreUsuario">{{ request.session.usuario_solicitante.nombre}} {{ request.session.usuario_solicitante.apellido}}</div>
		<div class="bienvenido">Bienvenido:</div>
	</div>
	<div id="menuSup">
	    {% include 'proyectos/menu_superior.html' %}
		
	</div>
{% endblock %}

{% block contenido %}
	<div id="menuL">
	    {% include 'proyectos/menu_lateral.html' %}
	</div>
	<div class="WrapArea">
		<div class="bPaginas">
			<div class="tSeccion">
			{% block titulo_seccion %}{% endblock %}
			</div>
			<div class="separador"> </div>
			<div class="WrapAreaTra">
				<div id="panel_operaciones">
					<div id="panel_operaciones_crud">
						{% block panel_operaciones_crud %}{% endblock %}
					</div>
					<div class="separador"> </div>
					<div id="panel_operaciones_tareas">
						{% block panel_operaciones_tareas %}{% endblock %}
					</div>
				</div>
				{% block area_trabajo %}{% endblock %}
				
			</div>
        </div>
	</div>
{% endblock %}

proyectos/proyectos/templates/proyectos/dashboard.html
{% extends "proyectos/base.html" %}




{% block titulo_seccion %}
<img src="{{ MEDIA_URL }}/imagenes/tProyecto.png" width="300" height="50" />
{% endblock %}

{% block area_trabajo %}
<div class="WrapBackground" style="background-image:url({{ MEDIA_URL }}/imagenes/bgProyecto.png);"> </div>
{% endblock %}

proyectos/proyectos/templates/proyectos/ingresar_contrasena.html
{% extends "base.html" %}
{% block titulo %}::: AUTANA - Proyectos :::{% endblock %}

{% block contenido %}
	<script>
		
	</script>
	<div class="WrapAreaTra" style="background-image:url({{ MEDIA_URL }}/imagenes/bgPass.png); background-position:bottom right; background-repeat:no-repeat">

		
		{% if not mensaje_error %}
		    <form id="form_confirmar" enctype='multipart/form-data' method="post">
				{% csrf_token %}

				<div class="entrada">
					Ingrese su contraseña dos veces
					<br />
					<br />
				</div>
				<div class="principal">
            <div class="pIzq">
                *Pregunta de Seguridad: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.pregunta_seguridad }}
                </label>
            </div>            
        </div>
        <div class="principal">
            <div class="pIzq">
                *Respuesta: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.respuesta_seguridad }}
                </label>
            </div>            
        </div>
				<div class="principal">
					<div class="pIzq">*Contraseña:</div> 
					<div class="pDer">
						<label>
							{{ form.contrasena }}
							<div id="scorebarBorder" class="flotadoi" style="height: 14px;">
		                    	<div id="score" style="margin-top: 1px;">0%</div>
		                    	<div id="scorebar" >&nbsp;</div>
		                    </div>
						</label>
					</div>            
				</div>
				<div class="principal">
					<div class="pIzq">*Confirmar contraseña:</div> 
					<div class="pDer">
						<label>
							{{ form.conf_contrasena }}
						</label>
					</div>
				</div>
			  	<div class="principal">
			  		<div class="pDer">
			  			<div class="obligatorio1">(*) Datos obligatorios</div>
			  		</div>
				</div>
				<div class="principal">
					<input type="submit" value="Aceptar" />
				</div>
			</form>
		{% endif %}
	</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{{ MEDIA_URL }}/js/ingresa-contrasena.js"></script>
{% endblock %}

proyectos/proyectos/templates/proyectos/login.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link type="text/css" rel="stylesheet" href="{{ MEDIA_URL }}/css/login.css" />
        <link type="text/css" rel="stylesheet" href="{{ MEDIA_URL }}/css/smoothness/jquery-ui-1.9.2.custom.css" />
        <title>::: AUTANA - Proyectos :::</title>
    </head>
    <body>
        
        <div id="loading" style="" title="">
            <div class="loading_div">Cargando...</div>
        </div>
        <div id="wrap">
            <div id="header"> </div>
            <div id="banner"> </div>
            {% block mensajes %}
                {% if form.errors %}
                    <div class="msjerror">
                        No se pudo continuar con la aplicacion debido a los siguientes errores:<br/>
                        <ul>
                            {% for field in form %}
                                {% if field.errors %}<li>{{ field.errors|striptags }}</li>{% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
	            {% for message in messages %}
	                {% if 'success' in message.tags %}
	                    <div class="msjexito">{{ message }}</div>
	                {% elif 'info' in message.tags %}
	                    <div class="msjinfo">{{ message }}</div>
	                </div>
	                {% elif 'warning' in message.tags %}
	                    <div class="msjadv">{{ message }}</div>
	                {% elif 'error' in message.tags %}
	                    <div class="msjerror">{{ message }}</div>
	                {% elif 'debug' in message.tags %}
	                    <div class="msjadv">{{ message }}</div>
	                {% endif %}
	            {% endfor %}
            {% endblock mensajes %}
            
            <form id="form_login" enctype='multipart/form-data' method="post">
                {% csrf_token %}
                <div class="entrada">
                    <br />
                    <strong>Bienvenido al sistema AUTANA </strong>
                    <br />
                    <br />
                    Indique su RIF, contraseña y caracteres de la imagen para ingresar al sistema.
                </div>
                <div class="dEntrada">
                    <div class="dEnIzq">*RIF: </div> 
                    <div class="dEnDer">
                        {{ form.tipo_per }}
                        {{ form.rif }}-
                        {{ form.rif_fin }}
                    </div>
                </div>
                <div class="dEntrada">
                    <div class="dEnIzq">*Contraseña:</div>
                    <div class="dEnDer">
                        <label>
                            {{ form.contrasena }}
                        </label>
                    </div>
                </div>
                <div class="dEntrada">
                    <div class="obligatorio">(*) Datos obligatorios</div>
                </div>
                <div class="dRegistro">
                    <p><a href="{% url 'recuperar_contrasena' %}">¿Olvidó su contraseña?</a>
                    &nbsp;-&nbsp;
                    <a href="{% url 'registrar_solicitante' %}">¿Aún no se ha registrado?</a></p>
                </div>
                <div class="cont_captcha">
                    {{ form.captcha }}
                    <br />
                    <input type="submit" value="Ingresar" />
                </div>
            </form>
        </div>
        <div id="footer">
            Av Universidad, esquina "El Chorro", torre MCT, piso 18. Telf: (58212) 555.75.42 / 75.43<br />
            FAX: (58212) 555.77.17. Correo: fidetel@mcti.gob.ve
        </div>
    </body>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery/jquery-1.8.3.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery/jquery-ui-1.9.2.custom.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery/jquery.validate.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery/additional-methods.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery/custom-methods.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/util.js"></script>
        <script type="text/javascript" src="{{ MEDIA_URL }}/js/login.js"></script>
            <script type="text/javascript" src="{{ MEDIA_URL }}/js/jquery/jquery.counter-2.1.js"></script>
        <script>
        $("#img_captcha_refresh").attr('src', '{{ MEDIA_URL }}/imagenes/reload.png');
    
	    function refrescar_captcha()
	    {
	        $.ajax({
	            type: "GET",
	            url: '{% url 'refrescar_captcha' %}',
	            success: function(data)
	            {
	                var image_url = "{% url 'captcha-image' 0 %}"
	                image_url = image_url.replace('/0', '/' + data);
	                $('.captcha').attr('src', image_url);
	                $('#id_captcha_0').val(data);
	                $('#id_captcha_1').val('');
	            }
	        });         
	    }
        </script>
    
    <script>
        $(document).ready(function (){
            $('.qtip_arr_izq').qtip({
                position: {
                    my: 'right top', // Use the corner...
                    at: 'left top' // ...and opposite corner
                },
                style: {
                    classes: 'qtip-shadow qtip-tipped'
                }
            });
            $('.qtip_arr_der').qtip({
                position: {
                    my: 'left bottom', // Use the corner...
                    at: 'right top' // ...and opposite corner
                },
                style: {
                    classes: 'qtip-shadow qtip-tipped'
                }
            });
            
            $("#loading").dialog({
                autoOpen: false,
                height: 100,
                width: 200,
                modal: true,
                closeOnEscape: false,
                draggable: false,
                resizable: false,
                dialogClass: "no-titlebar",
            });
            
            $(document).ajaxStart(function() {
                $("#loading").dialog("open");
            }).ajaxStop(function() {
                $("#loading").dialog("close");
            });
        });
    </script>
    
</html>

proyectos/proyectos/templates/proyectos/menu_lateral.html
<div id="accordion">
	<h3>
		<img src="{{ MEDIA_URL }}/imagenes/bgUsuario.png" width="30"
			height="30" style="margin: 0 3px 0 12px;" />Usuario
	</h3>
	<div>
	   
		<ul style="list-style:none; margin-left:10px; padding:0px">
			{% if  request.session.ficha == CREAR_FICHA_USUARIO %} 
            <li>
                <a href="{% url 'crear_ficha' %}?tipo_usuario={{FICHA_NATURAL}}">
                Registrar persona natural
                </a>
            </li>
            <br/>
            <li>
                <a href="{% url 'crear_ficha' %}?tipo_usuario={{FICHA_JURIDICA}}">
                Registrar persona juridica
                </a>
            </li>				
			{% endif %}    
		</ul>
	</div>
	{% if MODIFICAR_USUARIO_SOLICITANTE in request.session.permisos %}
	<h3>
		<img src="{{ MEDIA_URL }}/imagenes/bgPass.png" width="30" height="30"
			style="margin: 0 3px 0 12px;" />Contraseña
	</h3>
	<div>
		<ul style="list-style:none; margin-left:10px; padding:0px">
			
			<li><a href="{% url 'recuperar_contrasena' %}">Cambiar
					contraseña </a></li>
		</ul>
	</div>
	{% endif %}
</div> <!-- accordion -->

proyectos/proyectos/templates/proyectos/menu_superior.html
{% if not request.session.usuario_solicitante == None %}
    <a href="{% url 'logout' %}">
        <img src="{{ MEDIA_URL }}/imagenes/iconos/salir.png" width="15" height="15" style="margin: 0 3px 0 6px;" />Salir
    </a>
{% endif %}

proyectos/proyectos/templates/proyectos/object_form.html
{% extends 'proyectos/base.html' %}


{% block panel_operaciones_crud %}
    <a class="guardar" href="javascript:" onclick="$('#form_ficha_natural').submit();"> </a>
{% endblock %}

{% block area_trabajo %}

<form method="post" enctype='multipart/form-data' id="form_ficha_natural">
                
                    {% csrf_token %}
                
<div id="tabsFormFichaNatural">
	<ul>
	<li><a href="#tabsNatural">Datos Solicitante</a></li>
	<li><a href="#tabsJuridica">Datos Institución</a></li>
	<li><a href="#tabsEmpleo">Datos Laborales</a></li>
	</ul>
	
	<div id="tabsNatural">
        <div class="principal">
            <div class="pIzq">*Nombres:
                <label>
                    {{ persona_form.nombre }}
                </label>
            </div>
            <div class="pDer">*Dirección:
                <label>
                    {{ persona_form.direccion }}
                </label>
            </div>
        </div>
        <br/>
        <div class="principal">
            <div class="pIzq">*Apellidos:
                <label>
                    {{ persona_form.apellido }}
                </label>
            </div>
        </div>
        <br/>
        <div class="principal">
            <div class="pIzq">*Cédula:
                <label>
                    {{ persona_form.tipo_per }}-{{ persona_form.rif }}
                </label>
            </div>
            <div class="pDer">*Teléfono:
                <label>
                    {{ persona_form.telefono }}
                </label>
            </div>
        </div>
        <br/>
        <div class="principal">
            <div class="pIzq">*F. Nacimiento:
                <label>
                    {{ persona_form.fecha_nacimiento }}
                </label>
            </div>
        </div>
        <br/>
        <div class="principal">
            <div class="pIzq">*Sexo:
                <label>
                    {{ persona_form.sexo }}
                </label>
            </div>
            <div class="pDer">*email:
                <label>
                    {{ persona_form.correo }}
                </label>
            </div>
        </div>
        <br/>
        <div class="principal">
            <div class="pIzq">*Estado civil:
                <label>
                    {{ persona_form.estado_civil }}
                </label>
            </div>
        </div>
        <br/>
        
        
	</div>
	
	<div id="tabsJuridica">
        <div class="principal">
			<div class="pIzq">*Nombre:
			    <label>
			        {{ empresa_form.razon_social }}
			    </label>
			</div>
			<div class="pDer">*Dirección:
                <label>
                    {{ empresa_form.direccion }}
                </label>
            </div>
		</div>
		<br />
		<div class="principal">
            <div class="pIzq">*Rif:
                <label>
                    {{ empresa_form.tipo_per }}-{{ empresa_form.rif }}-{{ empresa_form.rif_fin }}
                </label>
            </div>
            <div class="pDer">*Zona Postal:
                <label>
                    {{ empresa_form.zona_postal }}
                </label>
            </div>
        </div>
        <br />
        <div class="principal">
            <div class="pDer">*Telefono:
                <label>
                    {{ empresa_form.telefono }}
                </label>
            </div>
        </div>
        <br />
        <div class="principal">
            <div class="pIzq">*email:
                <label>
                    {{ empresa_form.correo }}
                </label>
            </div>
            <div class="pDer">*Área:
                <label>
                    {{ empresa_form.area }}
                </label>
            </div>
        </div>
        <br />
		<div class="principal">
            *Dirección Fiscal:
            {{ empresa_form.estado }} {{ empresa_form.municipio }} {{ empresa_form.parroquia }}    
	    </div>
	    <br/>
	</div>
	
	<div id="tabsEmpleo">
	{{form.as_p}}
	</div>
</div> <!-- tabs -->            
</form>
{% endblock %}

{% block extra_js %}
<script>
    $(document).ready(function (){
		$('#id_estado').change(function(event){
		                cargar_municipios($(this).val());
        });
        $('#id_municipio').change(function(event){
                cargar_parroquias($(this).val());
        });
	});


    function cargar_municipios(id_estado){
        if(id_estado!='')
        {
            $.ajax({
                url: "{% url 'obtener_municipios' %}",
                type: "GET",
                data: {
                    id_estado: id_estado
                },
                dataType: 'json',
                beforeSend: function(data) 
                {
                    $('#id_municipio').html('<option value="">Cargando...</option>');
                    $('#id_parroquia').html('<option value="">Cargando...</option>');
                },
                success: function(data) {
                    var options = '<option value="">Seleccione Municipio</option>';
                    for (var i = 0; i < data.length; i++)
                    {
                        options += '<option value="'+data[i]["id"]+'">' +data[i]["nombre"] +'</option>';
                    }
                    $('#id_municipio').html(options);
                    $("#id_municipio option:first").attr('selected', 'selected');
                }
            });
        }
        else
        {
             $('#id_municipio').html('<option value="">Seleccione Municipio</option>');
        }
        
        $('#id_parroquia').html('<option value="">Seleccione Parroquia</option>');
    };
    
    function cargar_parroquias(id_municipio)
        {
            if(id_municipio!='')
            {
                $.ajax({
                    url: "{% url 'obtener_parroquias' %}",
                    type: "GET",
                    data: {
                        id_municipio: id_municipio
                    },
                    dataType: 'json',
                    beforeSend: function(data) 
                    {
                        $('#id_parroquia').html('<option value="">Cargando...</option>');
                    },
                    success: function(data) {
                        var options = '<option value="">Seleccione Parroquia</option>';
                        for (var i = 0; i < data.length; i++)
                        {
                            options += '<option value="'+data[i]["id"]+'">' +data[i]["nombre"] +'</option>';
                        }
                        $('#id_parroquia').html(options);
                        $("#id_parroquia option:first").attr('selected', 'selected');
                    }
                });
            }
            else
            {
                 $('#id_parroquia').html('<option value="">Seleccione Parroquia</option>');
            }
        }

</script>

{% endblock %}

proyectos/proyectos/templates/proyectos/recuperar_contrasena.html
{% extends "base.html" %}
{% block titulo %}::: AUTANA - Proyectos :::{% endblock %}

{% block contenido %}
    <div class="WrapAreaTra" style="background-image:url({{ MEDIA_URL }}/imagenes/bgPass.png); background-position:bottom right; background-repeat:no-repeat">
        
        <form id="form_cambio_contrasena" enctype='multipart/form-data' method="post">
            {% csrf_token %}

            <div class="entrada">
                Ingrese su RIF y correo electrónico al cual enviar un vínculo de acceso al sistema
                <br />
                <br />
            </div>
            <div class="principal">
                <div class="pIzq">*RIF:</div> 
                <div class="pDer">
                    {{ form.tipo_per }}
                    {{ form.rif }}-
                    {{ form.rif_fin }}
                </div>
            </div>
            <div class="principal">
                <div class="pIzq">*Correo Electrónico: </div> 
                <div class="pDer">
                    <label>
                        {{ form.correo }}
                    </label>
                </div>
            </div>
             <div class="principal">
            <div class="pIzq">
                *Pregunta de Seguridad: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.pregunta_seguridad }}
                </label>
            </div>            
        </div>
        <div class="principal">
            <div class="pIzq">
                *Respuesta: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.respuesta_seguridad }}
                </label>
            </div>            
        </div>
                        
        
       
       
            <div class="principal">
                <div class="pDer">
                    <div class="obligatorio1">(*) Datos obligatorios</div>
                </div>
            </div>
            {% if not mensaje_exito %}
                <div class="cont_captcha">
                    {{ form.captcha }}
                    <br />
                    <input type="submit" value="Aceptar" />
                </div>
            {% endif %}
        </form>
        <div class="separadorv"> </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function (){
            $("#img_captcha_refresh").attr('src', '{{ MEDIA_URL }}/imagenes/reload.png');
          });
          function refrescar_captcha()
        {
            $.ajax({
                type: "GET",
                url: "{% url 'refrescar_captcha' %}",
                success: function(data)
                {
                    var image_url = "{% url 'captcha-image' 0 %}"
                    image_url = image_url.replace('/0', '/' + data);
                    $('.captcha').attr('src', image_url);
                    $('#id_captcha_0').val(data);
                    $('#id_captcha_1').val('');
                }
            });         
        }
    </script>
    <script type="text/javascript" src="{{ MEDIA_URL }}/js/recupera-contrasena.js"></script>
{% endblock %}

proyectos/proyectos/templates/proyectos/registro.html
{% extends "base.html" %}

{% block titulo %}::: AUTANA - Proyectos :::{% endblock %}

{% block contenido %}
    <form id="form_login" enctype='multipart/form-data' method="post">
        {% csrf_token %}
        <div class="entrada">
            Complete todos los campos para registrarse 
            <br />
            <br />
            <strong>Datos del Solicitante</strong>
        </div>
        <div class="principal">
            <div class="pIzq">
                *RIF: 
            </div> 
            <div class="pDer">
                {{ form.tipo_per }}
                {{ form.rif }}
                {{ form.rif_fin }}
                
            </div>            
        </div>
        <div class="principal">
            <div class="pIzq">
                *Nombres: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.nombre }}
                </label>
            </div>            
        </div>
        <div class="principal">
            <div class="pIzq">
                *Apellidos: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.apellido }}
                </label>
            </div>            
        </div>
        <div class="principal">
            <div class="pIzq">
                *Correo Electrónico: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.correo }}
                </label>
            </div>            
        </div>
       
        <div class="principal">
            <div class="pIzq">
                *Pregunta de Seguridad: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.pregunta_seguridad }}
                </label>
            </div>            
        </div>
        <div class="principal">
            <div class="pIzq">
                *Respuesta: 
            </div> 
            <div class="pDer">
                <label>
                    {{ form.respuesta_seguridad }}
                </label>
            </div>            
        </div>
        <div class="principal">
            <div class="pDer">
                <div class="obligatorio1">(*) Datos obligatorios</div>
            </div>
        </div>
        <div class="pCaptcha">
            {{ form.captcha }}
            <br />
            <input type="submit" value="Registrar" />
        </div>
    </form>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        $(document).ready(function (){
            $("#img_captcha_refresh").attr('src', '{{ MEDIA_URL }}/imagenes/reload.png');
          });
          function refrescar_captcha()
        {
            $.ajax({
                type: "GET",
                url: '{% url 'refrescar_captcha' %}',
                success: function(data)
                {
                    var image_url = "{% url 'captcha-image' 0 %}"
                    image_url = image_url.replace('/0', '/' + data);
                    $('.captcha').attr('src', image_url);
                    $('#id_captcha_0').val(data);
                    $('#id_captcha_1').val('');
                }
            });         
        }
        
        
    </script>
<script type="text/javascript" src="{{ MEDIA_URL }}/js/registro-solicitante.js"></script>

{% endblock %}